### ISSUE TITLE
Favorite boardgame(s)?

### ISSUE THREAD

**Issue by we3geeks** [atuttle/ama#1]
... including favorites played with kids. 

We're big fans of 7 Wonders and Carcassonne (including with our 8 year-old, third grade daughter), so we're always looking for recommendations sort of along those lines.

**Comment by atuttle** [comment]
Our current favorites are Settlers of Catan and, when the kids want in, Catan Junior. An 8YO would probably outgrow CJ pretty quickly, though classic Catan (and its expansions) provide almost unlimited replayability.

I'm also a big fan of Small World because while the mechanics and gameplay are really simple, the number of possible combinations of play characteristics is so huge, so again, replayability is super high.

We also like Castle Panic, which is cooperative, so the young'ns don't feel as hurt if they lose, because we all do. That said, I'm getting a little tired of this one. Replayability is not so great.

Fluxx is another one that I really like. There are (dozens?) of different flavors available... Family Fluxx is guaranteed kid + inlaw + etc friendly... but there's also Star Trek and Zombie variations...

My wife's favorite is Ticket to Ride, probably because until our last game night I think she had never lost to me. ;)

We also occasionally play Robot Turtles, which subversively teaches the kids how to write computer programs while still being fun for them. _Obvious motives are obvious._ :stuck_out_tongue_winking_eye:

I'm eager for the kids to be ready for more complex and difficult games like Carcassone. We play things like Exploding Kittens and Two Rooms and a Boom (both from Kickstarter) on teams so that the kids can participate without having to play on their own.

I grew up _hating_ board games because we never knew there was a whole universe of games outside of what Milton Bradley has on offer. You can only play so much Sorry! and Chutes and Ladders in your life, and I think I've pretty much hit my limit.
