### ISSUE TITLE
Thoughts on standing vs sitting desks

### ISSUE THREAD

**Issue by ryanguill** [atuttle/ama#2]
I know at one point you had transitioned to a standing desk - do you still use one? If not what changed? Any tips for someone else?

**Comment by atuttle** [comment]
If you can keep motivated, I think it's great. It's not a silver bullet, but it's a good thing. I definitely felt muscles in my back that were not accustomed to so much work that were sore for a while after I started... and I took that as a good sign.

If you can get a sit/stand convertible desk, it's worth it (probably? I don't have one... _yet_). There will be days that, for whatever reason, you just don't want to stand. So you sit with your laptop somewhere else. On the couch. In your desk chair across the room. Etc. And before you know it, it's been 2 weeks since you worked at your standing desk. And the ergonomics of sitting on the couch with your laptop are clearly worse than sitting at a desk, so it's a net loss.

Personally, I decided that if I was going to sit so much, I might as well convert my desk back to sitting - so I did. And sometimes I miss standing. Once I've got the spare cash, I want to get an [Ikea Bekant](http://www.ikea.com/us/en/catalog/products/S19022530/#/S09022540) desk so that I can convert back and forth on a whim. I have lots of whims. :wink:

**Comment by ryanguill** [comment]
When standing, how necessary do you feel were the right shoes or padded mat, things like that? Any suggestions on shoes or mats or other accessories?

**Comment by atuttle** [comment]
A mat is a necessity, no question. I spent $70 on something about 3/4" thick at Bed Bath & Beyond. It's done just fine.

Even with the mat, I found working barefoot to be hard on my feet. I usually just wear my running shoes.

Other than that, all that you need is to get the angles correct.

![image](https://cloud.githubusercontent.com/assets/46990/10377825/69986ac0-6dd3-11e5-8b2f-9af49a73596e.png)

**Comment by ryanguill** [comment]
:+1: thanks!

**Comment by atuttle** [comment]
I do still need to write a review for a standing desk related product that a manufacturer sent me... now that I think about it!
