### ISSUE TITLE
Skydiving

### ISSUE THREAD

**Issue by ryanguill** [atuttle/ama#3]
What motivates you to throw yourself out of a perfectly good airplane? How many times have you jumped?

**Comment by atuttle** [comment]
"Perfectly good" ~ you haven't seen our planes! :wink: 

I'll answer the easy question first: I have 89 jumps right now. My first was in 1999. All the rest are from between May 2014 and today. 1 of those from a hot air balloon! If the weather is good this weekend, I'm hoping to get 4-5 more.

The "why" question actually turns out to be pretty hard to answer, because it feels like there are 1,000 answers all competing for space in my head. Let's start here:

https://vimeo.com/44007931

But in my own words:

- Who _hasn't_ had the fantasy of being able to _fly_?!
- I've always been ambitious. I like a challenge, and I enjoy the process of getting better at stuff. Skydiving is incredibly challenging, while also being so much fun it feels criminal.
- It's actually a lot safer than most people tend think. Last year out of an estimated 3.2 million skydives made in the US, there were 24 deaths. (Excludes BASE jumping) That's 0.0075 deaths per 1,000 skydives. I've been jumping for almost a year and a half now and don't even have 100. (Granted, there are people that do thousands of jumps in a year, but they are jumping every weekend and probably some weekdays too. I jump about every 2-3 weeks on average)
- Did I mention it's fun? It's hard to find pictures of skydivers without a big cheesy smile on their face, and that's for a good reason.
- I am a firm believer that if you don't do the things you enjoy, you're wasting your life. There's never a "perfect" time to start something. There will always be a "well, maybe next year will be better" type of excuse available. From the time I saw skydiving in the X-Games on MTV when I was a wee little teenager I knew it was something I wanted to try. When I made my first jump as a 17th birthday gift, I knew it was something I would do for the rest of my life. (I gave it up to focus on school and starting my family from ~2000 to 2014.) Here's a few quotes that I think embody this sentiment well, in case I'm not being eloquent enough:
  - Life should not be a journey to the grave with the intention of arriving safely in a pretty and well preserved body, but rather to skid in broadside in a cloud of smoke, thoroughly used up, totally worn out, and loudly proclaiming "Wow! What a Ride!" -- Hunter S. Thompson
  - A long life may not be good enough, but a good life is long enough. -- Benjamin Franklin
- I have a disease that may some day result in my spine fusing together, so I see limited mobility in my future. This harkens back to the previous bullet point about making the most of the time we have.
