### ISSUE TITLE
I am allergic to cats, but...

### ISSUE THREAD

**Issue by marcesher** [atuttle/ama#4]
When you graciously hosted me in your lovely home for a night, which included at least one cat, I did not react the way I normally do -- sneezing, itching, etc.

Why is that, do you think?

**Comment by atuttle** [comment]
If I recall correctly, we asked about allergies before you came. When we know someone with pet allergies is coming we try pretty hard to do a thorough vacuuming about 48 hours before they arrive to get rid of as much as possible and also to give whatever gets kicked up into the air a chance to come to rest again.

If it makes you feel any better, my brother in law is also allergic and hasn't been so lucky. Maybe it was just really good luck? :laughing: 

And just so you know, when I have occasion to be circling ~Marietta in a climbing Cessna 182 (which turns out to be fairly often!) I like to look out over the general vicinity of York and imagine that you're somewhere over there doing something cool.

**Comment by marcesher** [comment]
:+1:
