### ISSUE TITLE
Working Remote

### ISSUE THREAD

**Issue by ryanguill** [atuttle/ama#5]
How long have you been working remotely and do you have any insights / tips & tricks / things to watch out for?  Do you recommend it?  How do you stay connected with your team (personally and professionally)? How do you stay productive / organized with your team?

**Comment by atuttle** [comment]
Great questions!

I've been 100% remote since March 2nd 2012, so I'm coming up on 5 years. For the 3 years before that I was doing maybe 2 days per month remote on average, which was helpful in knowing that full time remote would work for me. I don't think it's a good fit for everyone, but it's turned out to work really well for me. 

The added time flexibility is a huge benefit. Before [AlumnIQ](http://www.alumniq.com) I was commuting more than an hour and a half each way into Philadelphia -- _which does have some perks that I miss_ -- but getting that 15 hours per week back to spend with my family has been amazing. I used to get up in the dark and more or less sneak out of the house, and not get home until sunset; and my wife took care of everything our kids needed while I was gone. Now I can make them breakfast and lunch almost every day, spend the morning with them, and get them onto the school bus before work. We even have time to do fun stuff like [playing programming games](http://adamtuttle.codes/giggle-driven-development/).

But the cost of that benefit is that you have to be able and willing to work even more solitarily than coding already is. It took me a while to get into a routine where I felt focused enough without an aid like a Pomodoro timer, but like most other things practice makes perfect. When I first started we were mostly consulting and it's hard to feel invested in a vision that doesn't even belong to your company. But as we've pivoted to our own products I've found it really easy to stay focused because the vision is partly mine and there's always more to do.

I would say not to focus too hard on creating the perfect environment. You don't need a sit-stand convertible desk and an Aeron chair (both of which I covet, neither of which I have) to get work done. There are times where I'll work for an entire week on my couch. Your physical environment can be just as much of a time-trap as futzing with IDE customizations. Some are helpful, but it's possible that you could spend a whole month doing nothing else which is obviously counterproductive.

So secure a "good-enough" space to work (if your family will ever be home while you're working, being able to close a door to keep them out is crucial) and get to work!

Tooling will depend on your team, but if your company is trying to be remote-friendly, it should really be "remote first" in the same way we make responsive websites that are "mobile first." You don't want band-aids that attempt to keep remote people in the loop, you want everyone defaulting to the tools that the remote folks are using, even if they're sitting right next to one another. For us, that's Slack for text chat, [appear.in](http://appear.in) for video chat, and Google Calendar for scheduling. Trello for big-picture organization, and GitHub pull requests for code reviews. Many things pipe information into our team Slack: Uptime monitoring, exception logging, other warnings (API key expirations, failed data-sync jobs, etc). We send almost no email to one another - mostly just the occasional support email reply that gets CC'd to the team to indicate it's been handled. And more recently we're moving toward using Docker for development environments, which has been really nice to know that we've got consistency across developer machines.

In the beginning I would get cabin fever kind of regularly, so to combat that I would dedicate a day every month or so to working out-of-the-house somewhere: A brewery, library, coffee shop -- anywhere with free wifi and comfortable spots to sit. I haven't needed a day like that in maybe a year, but about half as often I end up visiting a client site or traveling for work. If I lived in Philly I might consider a membership at a coworking space like [Indy Hall](http://www.indyhall.org/).

Recently my team went for a brief camping trip that we called Code Camp. We coded all day and stayed up really late coding, something that we can only realistically get done when freed of the bonds of being at home. And we talked a lot of strategy during the drives. Beyond that, just normal reasons for getting together: We went to a team member's daughter's first birthday party and just hung out for the afternoon.

I'm starting to get the idea that productivity is a function of how important you feel your work is. If something feels important and urgent I have no trouble at all focusing on it all day long with no breaks. I have two alarms set on my watch to remind me to take lunch in case I blow it off for too long. I don't feel too bad about things that don't get done because there were things that were more important & urgent -- that makes me feel like what I'm working on is really high-impact.

If it's within your power, and you need to get something done that doesn't feel important (but perhaps a VIP is demanding it), you can incentivize yourself or your team with a cash bonus, or even just grant the freedom to work on something interesting & fun that would have otherwise been passed over because of things that contribute more to the bottom line.

I hope that answers your questions! :)
