### ISSUE TITLE
CF 2016 API Manager?

### ISSUE THREAD

**Issue by TAllenSr** [atuttle/ama#6]
As an expert on all things REST on CF, have you had a chance to evaluate the new API Manager in CF 2016 Enterprise?

**Comment by atuttle** [comment]
Short answer: I haven't.

I still maintain Taffy for my own needs and any issues that come up (few and far between); but otherwise I am slowly backing away from ColdFusion. We use it in our products at work but we've committed to migrating away -- a slow process since we have so much code. So I still use it, but it remains my #1 source for stress-related hair loss and inspiration for most of my cursing.

I haven't touched any version of CF beyond CF11. There's no point in me doing so because we won't be upgrading at work and I won't be using it elsewhere.
